version: '3.3'

services:
  test-database:
    image: postgres:16-alpine
    ports:
      - 15432:5432
    volumes:
      - ./.local/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=ttm_test_suite
      - POSTGRES_DB=ttm_test_database
